export const listBanks = [
  'Banco do Brasil',
  'Caixa Econômica Federal',
  'Itaú Unibanco',
  'Bradesco',
  'Santander',
  'Banco Safra',
  'BTG Pactual',
  'Banco Votorantim (BV)',
  'Banco Original',
  'Banco Pan',
  'Banco Inter',
  'Nubank',
  'Banco Neon',
  'Banco Modal',
  'Banco Daycoval',
  'Banco BMG',
  'Banco Pine',
  'Banco Alfa',
  'Banco Sofisa',
  'Banco Mercantil do Brasil',
  'Banco Indusval & Partners (BI&P)',
  'Banco ABC Brasil',
  'Banco Rendimento',
  'Banco Fibra',
];
