export const listBanks = [
  { label: 'Banco do Brasil', value: 'Banco do Brasil' },
  { label: 'Caixa Econômica Federal', value: 'Caixa Econômica Federal' },
  { label: 'Itaú Unibanco', value: 'Itaú Unibanco' },
  { label: 'Bradesco', value: 'Bradesco' },
  { label: 'Santander', value: 'Santander' },
  { label: 'Banco Safra', value: 'Banco Safra' },
  { label: 'BTG Pactual', value: 'BTG Pactual' },
  { label: 'Banco Votorantim (BV)', value: 'Banco Votorantim (BV)' },
  { label: 'Banco Original', value: 'Banco Original' },
  { label: 'Banco Pan', value: 'Banco Pan' },
  { label: 'Banco Inter', value: 'Banco Inter' },
  { label: 'Nubank', value: 'Nubank' },
  { label: 'Banco Neon', value: 'Banco Neon' },
  { label: 'Banco Modal', value: 'Banco Modal' },
  { label: 'Banco Daycoval', value: 'Banco Daycoval' },
  { label: 'Banco BMG', value: 'Banco BMG' },
  { label: 'Banco Pine', value: 'Banco Pine' },
  { label: 'Banco Alfa', value: 'Banco Alfa' },
  { label: 'Banco Sofisa', value: 'Banco Sofisa' },
  { label: 'Banco Mercantil do Brasil', value: 'Banco Mercantil do Brasil' },
  { label: 'Banco Indusval & Partners (BI&P)', value: 'Banco Indusval & Partners (BI&P)' },
  { label: 'Banco ABC Brasil', value: 'Banco ABC Brasil' },
  { label: 'Banco Rendimento', value: 'Banco Rendimento' },
  { label: 'Banco Fibra', value: 'Banco Fibra' },
];
